# Generated by Django 5.2 on 2026-03-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='descricao',
            field=models.CharField(),
        ),
    ]
