# Generated by Django 5.2.12 on 2026-03-12 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pedido_item_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_pedido',
            name='quantidade',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
