# Generated by Django 5.2.12 on 2026-03-20 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=100)),
                ('data', models.IntegerField()),
                ('imagem', models.ImageField(upload_to='filmes/')),
            ],
        ),
    ]
